<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>lin-modules</artifactId>
        <groupId>com.lin</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>lin-module-admin</artifactId>
    <description>后台管理接口模块</description>

    <dependencies>
        <dependency>
            <groupId>com.lin</groupId>
            <artifactId>lin-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.lin</groupId>
            <artifactId>lin-common-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>com.lin</groupId>
            <artifactId>lin-common-ratelimiter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.lin</groupId>
            <artifactId>lin-common-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.lin</groupId>
            <artifactId>lin-common-crypto</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <version>4.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>
